### ISSUE TITLE
Sender hangs when the file size is a multiple of 4096

### ISSUE THREAD

**Issue by kanna5** [magic-wormhole/magic-wormhole.rs#152]
To reproduce:

```bash
dd if=/dev/zero of=test.bin bs=4096 count=123
wormhole-rs send test.bin
```

The receiver will exit once all the contents of the file have been received, but the sender will hang until `ctrl+c` is pressed twice.

**Comment by aeshirey** [comment]
Newbie here interested in contributing.

It looks like the cause of this is in [`transfer::v1::send_records`](https://github.com/magic-wormhole/magic-wormhole.rs/blob/b6a471a67dd1158303f65aee3848ae6a5b72a48f/src/transfer/v1.rs?q=4096#L401) where the async read is performed. In the case of an input of size 4096, there's nothing left to read, so the sender somehow just spins. ¯\\\_(ツ)\_/¯

Fortunately, this function receives `file_size`, so it looks like this should be a straightforward fix:

```rust
if n < 4096 {
    break;
} else if sent_size == file_size {
    // multiple of 4096
    break;
}
```

I already verified that @kanna5's `dd` input hangs the sender and that this additional check fixes it. Happy to submit a PR. I'm curious why the current check doesn't simply do this, though?

**Comment by piegamesde** [comment]
Thanks for having a look. I'm not sure about checking `sent_size == file_size`, since this may go bad if the file is modified concurrently (time of check vs time of use). We could do `if n < 4096 || sent_size >= file_size`, but this would still hang if the file was concurrently truncated to a multiple of 4096 bytes. This would be an acceptable compromise for me, but there really should be a better solution to this.

**Comment by aeshirey** [comment]
Ah, you're right. In my rudimentary testing, it didn't appear to be the case:

```rust
eprintln!("Reading...");
let n = file.read(&mut plaintext[..]).await?;
eprintln!("Read {n} bytes");
```

"Read 0 bytes" never showed up, maybe the progress bar hampering stdout? But `assert!(n > 0)` crashes.
