### ISSUE TITLE
Play nice with Web Assembly

### ISSUE THREAD

**Issue by alex** [magic-wormhole/magic-wormhole.rs#2]
This is a big pony (🐴 ), but it'd be amazing if magic-wormhole.rs worked well under Web Assembly.

My reason for wanting this is that I've long wanted to package magic-wormhole up as a browser extension, but my desire to write JS is nil. I've often joked about wanting to do a magic-wormhole Rust implementation and use WASM, so the fact that you're working on this is amzing!

**Comment by warner** [comment]
Mind you, the amount of JS you'd need to write for the platform-specific IO layer might be considerable..

**Comment by warner** [comment]
Does this require `nostd`? Or providing a memory allocator of some sort?

**Comment by warner** [comment]
I started experimenting with this over the weekend. Two stumbling blocks I've hit so far:

* we use `sodiumoxide`, and of course that must compile a large C library, which fails under WASM. We're only using it for `SecretBox`, so I think we can replace this with the libsodium-compatible [XChaCha20Poly1305 support](https://github.com/RustCrypto/AEADs/blob/master/chacha20poly1305/src/xchacha20poly1305.rs) that was recently added to the [chacha20poly1305](https://crates.io/crates/chacha20poly1305) crate (under the [RustCrypto AEADs](https://github.com/RustCrypto/AEADs) umbrella). #58 is the place for this.
* the `magic-wormhole` -> `spake2` -> `curve25519-dalek` -> `clear_on_drop` dependency pathway gets us a [clear_on_drop](https://crates.io/crates/clear_on_drop) crate that uses a C file to do some assembly-language tricks to zeroize dropped secret-key buffers. It has a feature flag (`no_cc`) to disable this, but it's not our direct dependency (yet: #63). So we'd need a way to ask `spake2` to set a flag that asks `curve25519-dalek` to set a flag that asks `clear_on_drop` to avoid the C compile.

I don't know what other problems we'll hit. I was able to bypass the first one by just replacing all our symmetric crypto with no-ops, but I don't know how to get past the second one. Maybe there's some Cargo.toml/Cargo.lock wizardry that lets you set features for a transitive-dependency? Or maybe I should check out local copies of the whole dependency chain, and modify all of their Cargo.toml's to use `path=` dependencies on everything, so I can edit it all in-place.

**Comment by warner** [comment]
Once we get the core library compiling to WASM, the next step is to write JS glue code to satisfy its IO needs. The core is written as a function that accepts "events" from the outside world, and returns a list of actions. The application-facing API consists of API events like `AllocateCode` and `Send`, and result actions like `GotCode` and `GotMessage`. When the core needs IO to be performed, it returns an action like `WebSocketOpen`, and expects to eventually be given an event like `WebSocketConnectionMade` and `WebSocketMessageReceived`:

https://github.com/warner/magic-wormhole.rs/blob/a8b9cc32d9ccaca6a08de9d9f547adc9129f1d53/src/core/api.rs#L169-L186

So the JS glue needs to react to these actions with things like `new WebSocket(url)` and wiring up the handlers to deliver inbound data to the core. And it needs to peel off the API actions and return them to the JS "application", maybe through an EventEmitter or something.

We don't have any `Transit` code in magic-wormhole.rs yet, so we're limited to text-message transfers, and custom applications (i.e. a different APPID) that are content with small store-and-forward payloads. I've started poking at the Dilation work that would enable bulk transfers, but I need to finish some of the Python-side code (backwards compatibility with the Transit-based clients) before I'm likely to make too much progress on the Rust equivalent. (I don't intend to implement Transit in `magic-wormhole.rs`, but of course it'll be a lot easier to get away with that once I've shipped a python version that includes Dilation).

Any thoughts on what the JS API ought to be? My instinct is to make it look like the python Deferred API, where you create a `Wormhole` object and call methods on it which return Promises. But maybe something that takes `.on('message', cb)` would be more idiomatic? Or, I guess we could do both?

**Comment by warner** [comment]
Ok the second problem will be solved by an upcoming release of `curve25519-dalek` that switches to use `zeroize` instead of `clear_on_drop` (which depends upon `zeroize-1.0` being finalized, but that sounds like it may happen soon). So we can just wait for that release.

**Comment by warner** [comment]
@burdges pointed out that cargo features are additive, so if the glue code declares its own dependency upon `clear_on_drop = { .. features = ["no_cc"] }`, then that'll push the `no_cc` all the way down the dependency graph. With that trick (and a change to `magic-wormhole.rs` to replace `rustc-serialize` with `hex`), I'm able to get the glue code to compile.

**Comment by piegamesde** [comment]
The sodiumoxide issue is resolved now, can anyone knowing and interested in WASM give this a second try?

**Comment by corbinu** [comment]
@piegamesde I would be happy to take a run at it. I have been thinking especially since I love magic-wormhole would be interesting to have a static site up that was a WASM version for my non-cli friends and family. Would you be interested in that being a direct part of the project or should I just test as a library and possibly build it separately?

**Comment by piegamesde** [comment]
@corbinu Great! Yeah, we're all dreaming of this :)

> Would you be interested in that being a direct part of the project or should I just test as a library and possibly build it separately?

Tough question. I suggest you to try to include Wormhole as a library first, and if this doesn't work, we'll can talk about integrating it into the repository.

**Comment by andipabst** [comment]
I wanted to poke around this a little since I'd really love to use magic wormhole on the go in a browser (since a browser is just ubiquitous these days). I don't have any problem with writing the JavaScript wrapper/interop, but I don't really have much Rust experience.

So I tried to include magic-wormhole as a library, as you suggested @piegamesde.
```toml
magic-wormhole = { git = "https://github.com/magic-wormhole/magic-wormhole.rs", tag = "0.2.0"}
```

But unfortunately I can't get it to build as wasm. I could get around missing C-libraries by adjusting the build target `wasm32-unknown-emscripten` or `wasm32-wasi`. But now I am stuck since some libraries (e.g. `socket2` for websocket) just are not available for wasm. That of course makes sense, since the browser/javascript would handle the websocket connections as part of the IO wrapper around magic-wormhole.rs

I have created a [minimal example repository](https://github.com/andipabst/magic-wormhole-wasm) based on the `wasm-pack-template` for reference.

Could you please point me in the right direction on how to include/build this for wasm as a library?

**Comment by piegamesde** [comment]
@andipabst thanks for looking into this. First of all, please use some recent commit instead of a release. The last release has been a while ago (sorry about that).

As far as I can tell `socket2` is not part of our WebSockets stack. (The latter may be problematic as well, but one issue at a time.) We use `socket2` for finding a direct connection. For WASM, that feature must be hidden behind a cargo feature flag. (Feel free to just rip it out for now to get things working.) There are some transitive dependencies of `socket2` too (namely, `async-io` because of `async-std`). I don't really know how to fix that one yet.

**Comment by andipabst** [comment]
@piegamesde Thanks for your support!
I had a look at it and could get rid of most errors by either ripping the code out or using cargo feature flags, as you suggested. 

Now the only thing left is the direct TCP Connection in transit.rs. How should this be approached? Maybe this could be implemented using Websockets and I also thought about using WebRTC for the communication. But I think in the end the transit relay might have to be adapted for this (e.g. to not only handle tcp connections, but also websocket connections). 
Or do you have another idea or concept?

**Comment by piegamesde** [comment]
> Now the only thing left is the direct TCP Connection in transit.rs. […] in the end the transit relay might have to be adapted for this

Indeed. We are in the process of extending the relay protocol to support WebSockets connections in addition to plain TCP. Some links that may help you with this:

- https://github.com/magic-wormhole/magic-wormhole-protocols/pull/16
- https://github.com/magic-wormhole/magic-wormhole-protocols/pull/10
- https://github.com/psanford/wormhole-william/pull/63
- https://github.com/magic-wormhole/magic-wormhole-transit-relay/pull/23

For a start, I suggest that you simply hardcode the default relay server and ignore the rest, as we already know that it supports WebSockets. Once it works, we can talk about implementing the necessary protocol extensions (I'd be willing to help with that).

**Comment by piegamesde** [comment]
@andipabst I see that you have some commits on your fork. Can you please take the changes that prepare the repository for WASM support (dependencies, feature flags, code gates) and PR them?

**Comment by andipabst** [comment]
Hi @piegamesde, I tried again for some time, but unfortunately I was not able to get it working completely. I have pushed my work in progress state in my [fork](https://github.com/andipabst/magic-wormhole.rs/tree/wasm-support-3) and in a separate repository for the [webapp](https://github.com/andipabst/magic-wormhole-wasm).

Should you decide to have a look at it and get it working, I would be happy to assist with the web part! But my Rust skills are simply not enough to get that part running at the moment.

**Comment by andipabst** [comment]
I had a look and it looks really good! Basing it on the target platform is a good idea, since I really had some trouble with the feature flag.
FYI, `wasm-pack` is building the package against the target `wasm32-unknown-unknown`.

I think it should be possible to include a `cargo build --target wasm32-unknown-unknown` into the CI pipeline, shouldn`t it?

**Comment by piegamesde** [comment]
Thanks! Actually I'm not that happy about all the `cfg` flags I simply spammed in the `transit` module, but it will have to do for now. I'm pretty certain that the current transit handshake does not work and needs to be adapted for WebSockets, but that shouldn't be too hard.

> I think it should be possible to include a cargo build --target wasm32-unknown-unknown into the CI pipeline, shouldn`t it?

Yes, that's the plan

**Comment by piegamesde** [comment]
I think the changes should now be ready for actually trying them out in a browser. Since I've never done any web development beyond most basic HTML+CSS, I fear I won't be able to help out much there.

As far as I understand, one of the next steps would be to provide a JavaScript interop API, because most websites are JS based. Let me know if I can help anything there

**Comment by andipabst** [comment]
Thanks for your changes! I implemented a basic wasm integration. I had to change some parts, since `std::time::Instant::now()` is not implemented for wasm, but it compiles and runs now until it reaches the handshake. 

Then I run into an issue, as you predicted: The handshake via the websocket relay server fails since it opens a new websocket connection to the relay server which then gets a "welcome" response instead of the expected handshake messages.

**Comment by piegamesde** [comment]
Actually, the handshake should work fine, even though I haven't really tested it yet. What you describes sound like you are trying to connect to the rendezvous server as relay. I'm not sure if the public relay server even has a WebSocket endpoint. You can use my test server though, it should be reachable as `tcp://piegames.de:4001` and `ws://piegames.de:4002`

**Comment by andipabst** [comment]
Thanks for the hint, that was indeed the issue :facepalm: 

I could use with your test server for developing on my machine, but for making a hosted version available I needed a secure websocket endpoint (wss://), so I had to dust off my old Hetzner server a bit and run my own relay server (behind a nginx proxy for letsencrypt ssl termination).

You can see the result here: https://magic-wormhole-wasm.netlify.app/ 
It is still very rough, but it's a proof of concept and it works :smile: :tada: 

So going forward, I will polish the code a bit more and then plan to separate the wasm package and my reference implementation of the web-app using it.

**Comment by piegamesde** [comment]
Oh I forgot to add the TLS reverse proxy to the endpoint, hence no WSS. To be honest though, I'm not sure that using TLS provides any additional security given that the transit protocol is built to work with plain TCP connections too. But I'll see if I can add it anyways, shouldn't hurt either.

**Comment by andipabst** [comment]
No worries. I totally agree with you, but when serving the website over https (which should definitely be done), browsers also require using secure websocket connections. (See e.g. https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#security_considerations)

**Comment by piegamesde** [comment]
Thanks for explaining. `wss://piegames.de/wormhole-transit-relay` should now work too

**Comment by piegamesde** [comment]
This is pretty cool, many thanks! However, I must admit that I have little knowledge about JavaScript and the npm ecosystem, so I wouldn't feel comfortable with pushing things there at the moment. Would you mind becoming the maintainer for the JavaScript bindings of wormhole-rs?

**Comment by piegamesde** [comment]
Your code looks okay on a first glance. Can you get some better error messages or maybe even a stack trace?

**Comment by piegamesde** [comment]
Ah well, that's easy: the default relay server deployment does not have WebSocket transport enabled yet, however that's the only thing web clients support. So you need to host your own relay, and configure the client correctly.

**Comment by meejah** [comment]
The Winden servers that LeastAuthority.com runs support WebSocket (indeed, https://winden.app is a Web client using WASM etc). The addresses are in the FAQ in the linked app, and are currently `wss://mailbox.mw.leastauthority.com/v1` and `wss://relay.mw.leastauthority.com` / `tcp://relay.mw.leastauthority.com:4001` for the relay.

Note that a "tcp-only" client can talk to a "websocket-only" client via that relay too.
